export type CognitiveState =
  | 'NEUTRAL'
  | 'BREAKTHROUGH'
  | 'PRE_INSIGHT_TENSION'
  | 'CONTRADICTION'
  | 'VALUE_CONFLICT'
  | 'GROWTH'
  | 'REGRESSION'
  | 'EXPLORATION'
  | 'CREATIVE_FLOW'
  | 'DEEP_FOCUS'
  | 'EMOTIONAL_INTENSITY'
  | 'EMOTIONAL_DETACHMENT'
  | 'SILENCE'
  | 'ANTICIPATION'
  | 'PARALLEL_THOUGHT'
  | 'SELF_REALIZATION'
  | 'LONG_RANGE_VISION';

